version: "3.9"

services:
  eureka:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - FX_API_URL=https://api.exchangerate.host/latest?base=USD&symbols=EUR
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
      - product-service

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
      - product-service
      - order-service

